export let blogs = [
    {
      "type_of": "article",
      "id": 2165750,
      "title": "How to Make a Retro 2D JavaScript Game Part 2",
      "description": "Let’s make this game interactive! We’ll add a player, movement controls, and falling items.  Note: If...",
      "readable_publish_date": "Dec 19",
      "slug": "how-to-make-a-retro-2d-javascript-game-part-2-6hg",
      "path": "/jeremycmorgan/how-to-make-a-retro-2d-javascript-game-part-2-6hg",
      "url": "https://dev.to/jeremycmorgan/how-to-make-a-retro-2d-javascript-game-part-2-6hg",
      "comments_count": 1,
      "public_reactions_count": 7,
      "collection_id": 29809,
      "published_timestamp": "2024-12-19T19:36:10Z",
      "positive_reactions_count": 7,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Frp3orabu0nlpb917lbjj.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Frp3orabu0nlpb917lbjj.png",
      "canonical_url": "https://www.howtomakegames.org/phaser-tutorials/how-to-make-2d-javascript-game-2/",
      "created_at": "2024-12-19T19:26:12Z",
      "edited_at": "2024-12-19T19:44:09Z",
      "crossposted_at": null,
      "published_at": "2024-12-19T19:36:10Z",
      "last_comment_at": "2024-12-20T06:39:11Z",
      "reading_time_minutes": 2,
      "tag_list": [
        "javascript",
        "gamedev",
        "beginners",
        "tutorial"
      ],
      "tags": "javascript, gamedev, beginners, tutorial",
      "user": {
        "name": "Jeremy Morgan",
        "username": "jeremycmorgan",
        "twitter_username": "JeremyCMorgan",
        "github_username": "JeremyMorgan",
        "user_id": 48220,
        "website_url": "https://www.jeremymorgan.com",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F48220%2F392b62cb-75f7-4107-9fc9-0c9e35794320.png",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F48220%2F392b62cb-75f7-4107-9fc9-0c9e35794320.png"
      }
    },
    {
      "type_of": "article",
      "id": 2161403,
      "title": "Top 7 Featured DEV Posts of the Week",
      "description": "Welcome to this week's Top 7, where the DEV editorial team handpicks their favorite posts from the...",
      "readable_publish_date": "Dec 17",
      "slug": "top-7-featured-dev-posts-of-the-week-k6m",
      "path": "/devteam/top-7-featured-dev-posts-of-the-week-k6m",
      "url": "https://dev.to/devteam/top-7-featured-dev-posts-of-the-week-k6m",
      "comments_count": 8,
      "public_reactions_count": 25,
      "collection_id": null,
      "published_timestamp": "2024-12-17T16:50:15Z",
      "positive_reactions_count": 25,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F1ul30na7h6rw5mued4nv.jpg",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F1ul30na7h6rw5mued4nv.jpg",
      "canonical_url": "https://dev.to/devteam/top-7-featured-dev-posts-of-the-week-k6m",
      "created_at": "2024-12-17T16:48:33Z",
      "edited_at": null,
      "crossposted_at": null,
      "published_at": "2024-12-17T16:50:15Z",
      "last_comment_at": "2024-12-19T15:09:42Z",
      "reading_time_minutes": 2,
      "tag_list": [
        "top7"
      ],
      "tags": "top7",
      "user": {
        "name": "dev.to staff",
        "username": "thepracticaldev",
        "twitter_username": "ThePracticalDev",
        "github_username": null,
        "user_id": 3,
        "website_url": "https://dev.to",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png"
      },
      "organization": {
        "name": "The DEV Team",
        "username": "devteam",
        "slug": "devteam",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg"
      }
    },
    {
      "type_of": "article",
      "id": 2161122,
      "title": "The history of game engines — from assembly coding to photorealism and AI",
      "description": "Modern games with photorealistic graphics and convincing physics are built on decades of...",
      "readable_publish_date": "Dec 17",
      "slug": "the-history-of-game-engines-from-assembly-coding-to-photorealism-and-ai-d9h",
      "path": "/ispmanager/the-history-of-game-engines-from-assembly-coding-to-photorealism-and-ai-d9h",
      "url": "https://dev.to/ispmanager/the-history-of-game-engines-from-assembly-coding-to-photorealism-and-ai-d9h",
      "comments_count": 1,
      "public_reactions_count": 12,
      "collection_id": null,
      "published_timestamp": "2024-12-17T13:55:49Z",
      "positive_reactions_count": 12,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fjgra9ntqv9o0iyv8g5ua.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fjgra9ntqv9o0iyv8g5ua.png",
      "canonical_url": "https://dev.to/ispmanager/the-history-of-game-engines-from-assembly-coding-to-photorealism-and-ai-d9h",
      "created_at": "2024-12-17T13:47:21Z",
      "edited_at": null,
      "crossposted_at": null,
      "published_at": "2024-12-17T13:55:49Z",
      "last_comment_at": "2024-12-18T16:15:40Z",
      "reading_time_minutes": 5,
      "tag_list": [
        "gamedev",
        "assembly",
        "coding",
        "ai"
      ],
      "tags": "gamedev, assembly, coding, ai",
      "user": {
        "name": "ispmanager.com",
        "username": "ispmanager_com",
        "twitter_username": "ispmanager_com",
        "github_username": null,
        "user_id": 1144203,
        "website_url": "https://www.ispmanager.com",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1144203%2F4d7f6935-7de9-4db0-91d5-b5c630367f28.png",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1144203%2F4d7f6935-7de9-4db0-91d5-b5c630367f28.png"
      },
      "organization": {
        "name": "Ispmanager",
        "username": "ispmanager",
        "slug": "ispmanager",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F7399%2Ffa7add1d-8292-4eab-b803-58adfeb901a5.png",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F7399%2Ffa7add1d-8292-4eab-b803-58adfeb901a5.png"
      }
    },
    {
      "type_of": "article",
      "id": 2162115,
      "title": "A conversation with your architecture",
      "description": "Over the course of my career I have worked on a number of sprawling software systems. One tool that...",
      "readable_publish_date": "Dec 18",
      "slug": "a-conversation-with-your-architecture-2mn",
      "path": "/aws/a-conversation-with-your-architecture-2mn",
      "url": "https://dev.to/aws/a-conversation-with-your-architecture-2mn",
      "comments_count": 0,
      "public_reactions_count": 8,
      "collection_id": null,
      "published_timestamp": "2024-12-18T18:00:00Z",
      "positive_reactions_count": 8,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fm6jpao51j0y84ucecw8b.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fm6jpao51j0y84ucecw8b.png",
      "canonical_url": "https://community.aws/content/2qM2qCmPCaAByW0bDVR7OdBo1dF/a-conversation-with-your-architecture",
      "created_at": "2024-12-18T03:00:20Z",
      "edited_at": null,
      "crossposted_at": null,
      "published_at": "2024-12-18T18:00:00Z",
      "last_comment_at": "2024-12-18T18:00:00Z",
      "reading_time_minutes": 7,
      "tag_list": [
        "aws",
        "ai",
        "architecture"
      ],
      "tags": "aws, ai, architecture",
      "user": {
        "name": "Jenna Pederson",
        "username": "jennapederson",
        "twitter_username": null,
        "github_username": "jennapederson",
        "user_id": 174967,
        "website_url": "https://www.jennapederson.com",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F174967%2F6a67f6e2-f078-4654-a441-ec5576074cba.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F174967%2F6a67f6e2-f078-4654-a441-ec5576074cba.jpg"
      },
      "organization": {
        "name": "AWS",
        "username": "aws",
        "slug": "aws",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1726%2Fe01690b9-c8bd-4eb9-bbe2-a4db25a702a9.png",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1726%2Fe01690b9-c8bd-4eb9-bbe2-a4db25a702a9.png"
      }
    },
    {
      "type_of": "article",
      "id": 2159259,
      "title": "Accessible, sustainable, and creative web development",
      "description": "Concluding my series about making our work and products more sustainable and breaking out of our...",
      "readable_publish_date": "Dec 16",
      "slug": "accessible-sustainable-and-creative-web-development-4im1",
      "path": "/ingosteinke/accessible-sustainable-and-creative-web-development-4im1",
      "url": "https://dev.to/ingosteinke/accessible-sustainable-and-creative-web-development-4im1",
      "comments_count": 4,
      "public_reactions_count": 18,
      "collection_id": 22597,
      "published_timestamp": "2024-12-16T13:17:15Z",
      "positive_reactions_count": 18,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fm9vtwjyj800uvggxay4m.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fm9vtwjyj800uvggxay4m.png",
      "canonical_url": "https://openmindculture.hashnode.dev/accessible-sustainable-and-creative-web-development",
      "created_at": "2024-12-16T13:15:26Z",
      "edited_at": "2024-12-17T13:40:02Z",
      "crossposted_at": null,
      "published_at": "2024-12-16T13:17:15Z",
      "last_comment_at": "2024-12-17T13:35:07Z",
      "reading_time_minutes": 3,
      "tag_list": [
        "a11y",
        "webdev"
      ],
      "tags": "a11y, webdev",
      "user": {
        "name": "Ingo Steinke, web developer",
        "username": "ingosteinke",
        "twitter_username": null,
        "github_username": "openmindculture",
        "user_id": 233697,
        "website_url": "https://www.ingo-steinke.com/",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F233697%2Fa99c74dd-6c7f-43fc-a778-e4299dc36238.png",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F233697%2Fa99c74dd-6c7f-43fc-a778-e4299dc36238.png"
      }
    },
    {
      "type_of": "article",
      "id": 2129133,
      "title": "Testing Different Navigation Options with Compose",
      "description": "One part of creating accessible Android apps is to provide alternative navigation options. Some...",
      "readable_publish_date": "Dec 4",
      "slug": "testing-different-navigation-options-with-compose-4055",
      "path": "/eevajonnapanula/testing-different-navigation-options-with-compose-4055",
      "url": "https://dev.to/eevajonnapanula/testing-different-navigation-options-with-compose-4055",
      "comments_count": 0,
      "public_reactions_count": 4,
      "collection_id": null,
      "published_timestamp": "2024-12-04T12:07:00Z",
      "positive_reactions_count": 4,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fwdnyfi5xhsrn1dbssd47.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fwdnyfi5xhsrn1dbssd47.png",
      "canonical_url": "https://eevis.codes/blog/2024-12-03/testing-different-navigation-options-with-compose/",
      "created_at": "2024-12-01T08:24:52Z",
      "edited_at": null,
      "crossposted_at": null,
      "published_at": "2024-12-04T12:07:00Z",
      "last_comment_at": "2024-12-04T12:07:00Z",
      "reading_time_minutes": 5,
      "tag_list": [
        "a11y",
        "android",
        "testing",
        "mobile"
      ],
      "tags": "a11y, android, testing, mobile",
      "user": {
        "name": "Eevis",
        "username": "eevajonnapanula",
        "twitter_username": null,
        "github_username": "eevajonnapanula",
        "user_id": 201004,
        "website_url": "https://eevis.codes",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F201004%2F0196665f-a91d-4692-a6d6-12e6d68737e2.png",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F201004%2F0196665f-a91d-4692-a6d6-12e6d68737e2.png"
      }
    },
    {
      "type_of": "article",
      "id": 2157022,
      "title": "Downsize your JavaScript: Mastering Bundler Optimizations",
      "description": "Introduction   Over the past 15 years, the JavaScript ecosystem has expanded rapidly,...",
      "readable_publish_date": "Dec 17",
      "slug": "downsize-your-javascript-mastering-bundler-optimizations-2485",
      "path": "/filipsobol/downsize-your-javascript-mastering-bundler-optimizations-2485",
      "url": "https://dev.to/filipsobol/downsize-your-javascript-mastering-bundler-optimizations-2485",
      "comments_count": 9,
      "public_reactions_count": 50,
      "collection_id": null,
      "published_timestamp": "2024-12-17T11:00:00Z",
      "positive_reactions_count": 50,
      "cover_image": null,
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fo7jpt9l3h4t0a2nycela.png",
      "canonical_url": "https://dev.to/filipsobol/downsize-your-javascript-mastering-bundler-optimizations-2485",
      "created_at": "2024-12-14T21:35:02Z",
      "edited_at": "2024-12-20T09:10:51Z",
      "crossposted_at": null,
      "published_at": "2024-12-17T11:00:00Z",
      "last_comment_at": "2024-12-19T12:42:17Z",
      "reading_time_minutes": 10,
      "tag_list": [
        "webdev",
        "javascript",
        "performance"
      ],
      "tags": "webdev, javascript, performance",
      "user": {
        "name": "Filip Sobol",
        "username": "filipsobol",
        "twitter_username": null,
        "github_username": "filipsobol",
        "user_id": 878039,
        "website_url": "https://bsky.app/profile/filipsobol.bsky.social",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F878039%2Fb08d89ac-fcc4-4ce3-a0aa-873599590841.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F878039%2Fb08d89ac-fcc4-4ce3-a0aa-873599590841.jpg"
      }
    },
    {
      "type_of": "article",
      "id": 2150352,
      "title": "Top 7 Featured DEV Posts of the Week",
      "description": "Welcome to this week's Top 7, where the DEV editorial team handpicks their favorite posts from the...",
      "readable_publish_date": "Dec 10",
      "slug": "top-7-featured-dev-posts-of-the-week-2e1e",
      "path": "/devteam/top-7-featured-dev-posts-of-the-week-2e1e",
      "url": "https://dev.to/devteam/top-7-featured-dev-posts-of-the-week-2e1e",
      "comments_count": 7,
      "public_reactions_count": 43,
      "collection_id": null,
      "published_timestamp": "2024-12-10T18:27:24Z",
      "positive_reactions_count": 43,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fil32u4jurwh71t43ydxi.jpg",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fil32u4jurwh71t43ydxi.jpg",
      "canonical_url": "https://dev.to/devteam/top-7-featured-dev-posts-of-the-week-2e1e",
      "created_at": "2024-12-10T18:27:25Z",
      "edited_at": "2024-12-10T19:40:53Z",
      "crossposted_at": null,
      "published_at": "2024-12-10T18:27:24Z",
      "last_comment_at": "2024-12-13T11:46:14Z",
      "reading_time_minutes": 2,
      "tag_list": [
        "top7"
      ],
      "tags": "top7",
      "user": {
        "name": "dev.to staff",
        "username": "thepracticaldev",
        "twitter_username": "ThePracticalDev",
        "github_username": null,
        "user_id": 3,
        "website_url": "https://dev.to",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png"
      },
      "organization": {
        "name": "The DEV Team",
        "username": "devteam",
        "slug": "devteam",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg"
      }
    },
    {
      "type_of": "article",
      "id": 2127228,
      "title": "What was your win this week?!",
      "description": "👋👋👋👋  Looking back on your week -- what was something you're proud of?  All wins count -- big or...",
      "readable_publish_date": "Dec 13",
      "slug": "what-was-your-win-this-week-7k6",
      "path": "/devteam/what-was-your-win-this-week-7k6",
      "url": "https://dev.to/devteam/what-was-your-win-this-week-7k6",
      "comments_count": 23,
      "public_reactions_count": 16,
      "collection_id": null,
      "published_timestamp": "2024-12-13T05:00:00Z",
      "positive_reactions_count": 16,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Ft2jygtd0iulkt8wyn81h.jpg",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Ft2jygtd0iulkt8wyn81h.jpg",
      "canonical_url": "https://dev.to/devteam/what-was-your-win-this-week-7k6",
      "created_at": "2024-11-29T17:51:03Z",
      "edited_at": null,
      "crossposted_at": null,
      "published_at": "2024-12-13T05:00:00Z",
      "last_comment_at": "2024-12-18T12:44:51Z",
      "reading_time_minutes": 1,
      "tag_list": [
        "weeklyretro",
        "discuss"
      ],
      "tags": "weeklyretro, discuss",
      "user": {
        "name": "Jess Lee",
        "username": "jess",
        "twitter_username": "jessleenyc",
        "github_username": "jessleenyc",
        "user_id": 264,
        "website_url": null,
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F264%2F40d89fb9-4de0-414d-8a06-f52ddda0bc75.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F264%2F40d89fb9-4de0-414d-8a06-f52ddda0bc75.jpg"
      },
      "organization": {
        "name": "The DEV Team",
        "username": "devteam",
        "slug": "devteam",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg"
      },
      "flare_tag": {
        "name": "discuss",
        "bg_color_hex": "#71EA8B",
        "text_color_hex": "#FFFFFF"
      }
    },
    {
      "type_of": "article",
      "id": 2127222,
      "title": "What was your win this week?",
      "description": "👋👋👋👋  Looking back on your week -- what was something you're proud of?  All wins count -- big or...",
      "readable_publish_date": "Dec 6",
      "slug": "what-was-your-win-this-week-2m3o",
      "path": "/devteam/what-was-your-win-this-week-2m3o",
      "url": "https://dev.to/devteam/what-was-your-win-this-week-2m3o",
      "comments_count": 16,
      "public_reactions_count": 5,
      "collection_id": null,
      "published_timestamp": "2024-12-06T12:45:00Z",
      "positive_reactions_count": 5,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fiyd83pd8j81sisqyso4h.jpg",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fiyd83pd8j81sisqyso4h.jpg",
      "canonical_url": "https://dev.to/devteam/what-was-your-win-this-week-2m3o",
      "created_at": "2024-11-29T17:46:13Z",
      "edited_at": null,
      "crossposted_at": null,
      "published_at": "2024-12-06T12:45:00Z",
      "last_comment_at": "2024-12-09T23:25:57Z",
      "reading_time_minutes": 1,
      "tag_list": [
        "weeklyretro",
        "discuss"
      ],
      "tags": "weeklyretro, discuss",
      "user": {
        "name": "Jess Lee",
        "username": "jess",
        "twitter_username": "jessleenyc",
        "github_username": "jessleenyc",
        "user_id": 264,
        "website_url": null,
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F264%2F40d89fb9-4de0-414d-8a06-f52ddda0bc75.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F264%2F40d89fb9-4de0-414d-8a06-f52ddda0bc75.jpg"
      },
      "organization": {
        "name": "The DEV Team",
        "username": "devteam",
        "slug": "devteam",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg"
      },
      "flare_tag": {
        "name": "discuss",
        "bg_color_hex": "#71EA8B",
        "text_color_hex": "#FFFFFF"
      }
    },
    {
      "type_of": "article",
      "id": 2159797,
      "title": "My Top Cursor Tips (v0.43)",
      "description": "I've been using Cursor extensively for 4 months in both professional and hobby ways, mostly on...",
      "readable_publish_date": "Dec 16",
      "slug": "my-top-cursor-tips-v043-1kcg",
      "path": "/heymarkkop/my-top-cursor-tips-v043-1kcg",
      "url": "https://dev.to/heymarkkop/my-top-cursor-tips-v043-1kcg",
      "comments_count": 3,
      "public_reactions_count": 9,
      "collection_id": null,
      "published_timestamp": "2024-12-16T21:38:22Z",
      "positive_reactions_count": 9,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fa1ni1hip5lznh8kr01m2.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fa1ni1hip5lznh8kr01m2.png",
      "canonical_url": "https://dev.to/heymarkkop/my-top-cursor-tips-v043-1kcg",
      "created_at": "2024-12-16T20:00:27Z",
      "edited_at": "2024-12-16T21:40:03Z",
      "crossposted_at": null,
      "published_at": "2024-12-16T21:38:22Z",
      "last_comment_at": "2024-12-19T06:47:38Z",
      "reading_time_minutes": 6,
      "tag_list": [
        "tutorial",
        "ai",
        "productivity",
        "learning"
      ],
      "tags": "tutorial, ai, productivity, learning",
      "user": {
        "name": "Mark Kop",
        "username": "heymarkkop",
        "twitter_username": "HeyMarkKop",
        "github_username": "Markkop",
        "user_id": 217830,
        "website_url": "https://www.linkedin.com/in/marcelo-kopmann/",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F217830%2F71496d44-8c01-4e86-bc10-1b98ae120003.png",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F217830%2F71496d44-8c01-4e86-bc10-1b98ae120003.png"
      }
    },
    {
      "type_of": "article",
      "id": 2157473,
      "title": "What Do You Think About Feature-Sliced Design (FSD)?",
      "description": "Feature-Sliced Design (FSD) is gaining attention as a methodology for structuring frontend projects....",
      "readable_publish_date": "Dec 15",
      "slug": "what-do-you-think-about-feature-sliced-design-fsd-25a8",
      "path": "/m_midas/what-do-you-think-about-feature-sliced-design-fsd-25a8",
      "url": "https://dev.to/m_midas/what-do-you-think-about-feature-sliced-design-fsd-25a8",
      "comments_count": 3,
      "public_reactions_count": 11,
      "collection_id": null,
      "published_timestamp": "2024-12-15T10:15:34Z",
      "positive_reactions_count": 11,
      "cover_image": null,
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fk788qxm9x1y59owkpugz.png",
      "canonical_url": "https://dev.to/m_midas/what-do-you-think-about-feature-sliced-design-fsd-25a8",
      "created_at": "2024-12-15T10:15:35Z",
      "edited_at": null,
      "crossposted_at": null,
      "published_at": "2024-12-15T10:15:34Z",
      "last_comment_at": "2024-12-18T16:18:31Z",
      "reading_time_minutes": 1,
      "tag_list": [
        "discuss",
        "webdev",
        "javascript",
        "programming"
      ],
      "tags": "discuss, webdev, javascript, programming",
      "user": {
        "name": "Yan Levin",
        "username": "m_midas",
        "twitter_username": null,
        "github_username": "midas-png",
        "user_id": 1121962,
        "website_url": null,
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1121962%2Fed2131d9-386d-4110-b5a9-84806a56663c.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1121962%2Fed2131d9-386d-4110-b5a9-84806a56663c.jpg"
      },
      "flare_tag": {
        "name": "discuss",
        "bg_color_hex": "#71EA8B",
        "text_color_hex": "#FFFFFF"
      }
    },
    {
      "type_of": "article",
      "id": 2161144,
      "title": "What is shift-left ⬅️ programming?",
      "description": "Rust 🦀 is the ultimate shift-left programming language!  If Shift-left testing means that we...",
      "readable_publish_date": "Dec 17",
      "slug": "what-is-shift-left-programming-5601",
      "path": "/szabgab/what-is-shift-left-programming-5601",
      "url": "https://dev.to/szabgab/what-is-shift-left-programming-5601",
      "comments_count": 25,
      "public_reactions_count": 57,
      "collection_id": null,
      "published_timestamp": "2024-12-17T14:04:20Z",
      "positive_reactions_count": 57,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fotmw6fizdpt2pib7ckjy.jpg",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fotmw6fizdpt2pib7ckjy.jpg",
      "canonical_url": "https://szabgab.com/shift-left-programming",
      "created_at": "2024-12-17T14:04:10Z",
      "edited_at": "2024-12-19T12:36:53Z",
      "crossposted_at": null,
      "published_at": "2024-12-17T14:04:20Z",
      "last_comment_at": "2024-12-19T23:53:13Z",
      "reading_time_minutes": 2,
      "tag_list": [
        "rust",
        "programming",
        "beginners"
      ],
      "tags": "rust, programming, beginners",
      "user": {
        "name": "Gabor Szabo",
        "username": "szabgab",
        "twitter_username": "szabgab",
        "github_username": "szabgab",
        "user_id": 36720,
        "website_url": "https://szabgab.com",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F36720%2F9b6106f4-f64e-47c6-8963-82a80ca0eda4.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F36720%2F9b6106f4-f64e-47c6-8963-82a80ca0eda4.jpg"
      }
    },
    {
      "type_of": "article",
      "id": 2150634,
      "title": "Just Launched: Shopify’s BORING Edition!",
      "description": "We are partnering to share relevant new software releases and are excited to share this launch by...",
      "readable_publish_date": "Dec 11",
      "slug": "just-launched-shopifys-boring-edition-10p5",
      "path": "/devteam/just-launched-shopifys-boring-edition-10p5",
      "url": "https://dev.to/devteam/just-launched-shopifys-boring-edition-10p5",
      "comments_count": 2,
      "public_reactions_count": 83,
      "collection_id": null,
      "published_timestamp": "2024-12-11T16:40:51Z",
      "positive_reactions_count": 83,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fznb2600q9c9t5bt9ef2n.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fznb2600q9c9t5bt9ef2n.png",
      "canonical_url": "https://dev.to/devteam/just-launched-shopifys-boring-edition-10p5",
      "created_at": "2024-12-10T23:04:43Z",
      "edited_at": null,
      "crossposted_at": null,
      "published_at": "2024-12-11T16:40:51Z",
      "last_comment_at": "2024-12-11T20:49:47Z",
      "reading_time_minutes": 2,
      "tag_list": [
        "shopify",
        "api",
        "news",
        "webdev"
      ],
      "tags": "shopify, api, news, webdev",
      "user": {
        "name": "DEV Launches",
        "username": "launches",
        "twitter_username": null,
        "github_username": null,
        "user_id": 2554644,
        "website_url": "https://dev.to",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F2554644%2Fc6d1879a-1215-4bad-9856-a6cc3d5010a7.png",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F2554644%2Fc6d1879a-1215-4bad-9856-a6cc3d5010a7.png"
      },
      "organization": {
        "name": "The DEV Team",
        "username": "devteam",
        "slug": "devteam",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg"
      },
      "flare_tag": {
        "name": "news",
        "bg_color_hex": "#111111",
        "text_color_hex": "#fff9ac"
      }
    },
    {
      "type_of": "article",
      "id": 2159359,
      "title": "Meme Monday",
      "description": "Meme Monday!  Today's cover image comes from last week's thread.  DEV is an inclusive space! Humor in...",
      "readable_publish_date": "Dec 16",
      "slug": "meme-monday-8hm",
      "path": "/ben/meme-monday-8hm",
      "url": "https://dev.to/ben/meme-monday-8hm",
      "comments_count": 48,
      "public_reactions_count": 28,
      "collection_id": null,
      "published_timestamp": "2024-12-16T14:01:42Z",
      "positive_reactions_count": 28,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F2hcwymluy7ih6mf4bvdm.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F2hcwymluy7ih6mf4bvdm.png",
      "canonical_url": "https://dev.to/ben/meme-monday-8hm",
      "created_at": "2024-12-16T14:01:42Z",
      "edited_at": null,
      "crossposted_at": null,
      "published_at": "2024-12-16T14:01:42Z",
      "last_comment_at": "2024-12-20T09:53:33Z",
      "reading_time_minutes": 1,
      "tag_list": [
        "discuss",
        "jokes",
        "watercooler"
      ],
      "tags": "discuss, jokes, watercooler",
      "user": {
        "name": "Ben Halpern",
        "username": "ben",
        "twitter_username": "bendhalpern",
        "github_username": "benhalpern",
        "user_id": 1,
        "website_url": "http://benhalpern.com",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1%2Ff451a206-11c8-4e3d-8936-143d0a7e65bb.png",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1%2Ff451a206-11c8-4e3d-8936-143d0a7e65bb.png"
      },
      "flare_tag": {
        "name": "discuss",
        "bg_color_hex": "#71EA8B",
        "text_color_hex": "#FFFFFF"
      }
    },
    {
      "type_of": "article",
      "id": 2145144,
      "title": "React 19 is now stable ! What’s New 👇",
      "description": "React 19 has arrived with exciting new features and improvements!  Hello Dev’s its me Md Taqui Imam,...",
      "readable_publish_date": "Dec 8",
      "slug": "react-19-is-now-stable-whats-new-1k3b",
      "path": "/random_ti/react-19-is-now-stable-whats-new-1k3b",
      "url": "https://dev.to/random_ti/react-19-is-now-stable-whats-new-1k3b",
      "comments_count": 18,
      "public_reactions_count": 132,
      "collection_id": null,
      "published_timestamp": "2024-12-08T12:43:56Z",
      "positive_reactions_count": 132,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Ffv5a0so7jplctnqf8zsv.jpeg",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Ffv5a0so7jplctnqf8zsv.jpeg",
      "canonical_url": "https://medium.com/p/b6fcbb4ae4c9",
      "created_at": "2024-12-08T10:25:19Z",
      "edited_at": "2024-12-15T16:36:17Z",
      "crossposted_at": null,
      "published_at": "2024-12-08T12:43:56Z",
      "last_comment_at": "2024-12-20T03:02:44Z",
      "reading_time_minutes": 3,
      "tag_list": [
        "webdev",
        "javascript",
        "react",
        "programming"
      ],
      "tags": "webdev, javascript, react, programming",
      "user": {
        "name": "Random",
        "username": "random_ti",
        "twitter_username": "Taquiimam14",
        "github_username": "taqui-786",
        "user_id": 1193992,
        "website_url": "https://mdtaquiimam.vercel.app",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1193992%2Ff72bad2f-7d5c-4d02-ac87-d2ec645042da.gif",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1193992%2Ff72bad2f-7d5c-4d02-ac87-d2ec645042da.gif"
      }
    },
    {
      "type_of": "article",
      "id": 2102829,
      "title": "Are you a practitioner in AI, Cloud Computing, or Cybersecurity and have been writing a newsletter for over 3 years? I'd love to chat with you. Reach out to me here: writenewsletters@gmail.com",
      "description": "A post by Anthony De Rosa",
      "readable_publish_date": "Nov 13",
      "slug": "are-you-a-practitioner-in-ai-cloud-computing-or-cybersecurity-and-have-been-writing-a-newsletter-for-over-3-years-id-love-to-chat-with-you-reach-out-to-me-here-writenewslettersgmailcom-2i3",
      "path": "/soupsoup/are-you-a-practitioner-in-ai-cloud-computing-or-cybersecurity-and-have-been-writing-a-newsletter-for-over-3-years-id-love-to-chat-with-you-reach-out-to-me-here-writenewslettersgmailcom-2i3",
      "url": "https://dev.to/soupsoup/are-you-a-practitioner-in-ai-cloud-computing-or-cybersecurity-and-have-been-writing-a-newsletter-for-over-3-years-id-love-to-chat-with-you-reach-out-to-me-here-writenewslettersgmailcom-2i3",
      "comments_count": 0,
      "public_reactions_count": 0,
      "collection_id": null,
      "published_timestamp": "2024-11-13T17:00:21Z",
      "positive_reactions_count": 0,
      "cover_image": null,
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fvc770cznz9hmhucuj3o8.png",
      "canonical_url": "https://dev.to/soupsoup/are-you-a-practitioner-in-ai-cloud-computing-or-cybersecurity-and-have-been-writing-a-newsletter-for-over-3-years-id-love-to-chat-with-you-reach-out-to-me-here-writenewslettersgmailcom-2i3",
      "created_at": "2024-11-13T17:00:21Z",
      "edited_at": null,
      "crossposted_at": null,
      "published_at": "2024-11-13T17:00:21Z",
      "last_comment_at": "2024-11-13T17:00:21Z",
      "reading_time_minutes": 0,
      "tag_list": [],
      "tags": "",
      "user": {
        "name": "Anthony De Rosa",
        "username": "soupsoup",
        "twitter_username": null,
        "github_username": "soupsoup",
        "user_id": 553527,
        "website_url": "https://antderosa.com",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F553527%2F02ac386b-7e7d-4dbb-b6c0-fd3878887223.png",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F553527%2F02ac386b-7e7d-4dbb-b6c0-fd3878887223.png"
      }
    },
    {
      "type_of": "article",
      "id": 2151563,
      "title": "Detecting and Analyzing Comment Quality Using Vector Search",
      "description": "There is a good chance you encounter vector search regularly, even if you are not building...",
      "readable_publish_date": "Dec 12",
      "slug": "detecting-and-analyzing-comment-quality-using-vector-search-45c4",
      "path": "/couchbase/detecting-and-analyzing-comment-quality-using-vector-search-45c4",
      "url": "https://dev.to/couchbase/detecting-and-analyzing-comment-quality-using-vector-search-45c4",
      "comments_count": 0,
      "public_reactions_count": 22,
      "collection_id": null,
      "published_timestamp": "2024-12-12T11:47:38Z",
      "positive_reactions_count": 22,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fe8k0tn00q1lxzfppng57.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fe8k0tn00q1lxzfppng57.png",
      "canonical_url": "https://www.couchbase.com/blog/vector-search-chrome-extension-content-quality/",
      "created_at": "2024-12-11T12:32:28Z",
      "edited_at": null,
      "crossposted_at": null,
      "published_at": "2024-12-12T11:47:38Z",
      "last_comment_at": "2024-12-12T11:47:38Z",
      "reading_time_minutes": 6,
      "tag_list": [
        "tutorial",
        "ai",
        "database",
        "vectordatabase"
      ],
      "tags": "tutorial, ai, database, vectordatabase",
      "user": {
        "name": "Ben Greenberg",
        "username": "bengreenberg",
        "twitter_username": "hummusonrails",
        "github_username": "hummusonrails",
        "user_id": 29526,
        "website_url": "https://www.hummusonrails.com",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F29526%2Fab3873ff-b15d-48ee-90c2-0006c40df4a1.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F29526%2Fab3873ff-b15d-48ee-90c2-0006c40df4a1.jpg"
      },
      "organization": {
        "name": "Couchbase",
        "username": "couchbase",
        "slug": "couchbase",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F6926%2Fc8d4aa0d-13b7-4b86-a6b2-1dabc361daa2.png",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F6926%2Fc8d4aa0d-13b7-4b86-a6b2-1dabc361daa2.png"
      }
    },
    {
      "type_of": "article",
      "id": 2075233,
      "title": "Introducing Vanilla Calendar Pro: A Simple, Customizable JavaScript Calendar Library",
      "description": "Adding a calendar component to your web application can be a powerful feature, whether you need it...",
      "readable_publish_date": "Nov 14",
      "slug": "introducing-vanilla-calendar-pro-a-simple-customizable-javascript-calendar-library-4c4n",
      "path": "/tmchuynh/introducing-vanilla-calendar-pro-a-simple-customizable-javascript-calendar-library-4c4n",
      "url": "https://dev.to/tmchuynh/introducing-vanilla-calendar-pro-a-simple-customizable-javascript-calendar-library-4c4n",
      "comments_count": 0,
      "public_reactions_count": 4,
      "collection_id": null,
      "published_timestamp": "2024-11-14T00:45:00Z",
      "positive_reactions_count": 4,
      "cover_image": null,
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F4akjr12levld5mg32ckb.png",
      "canonical_url": "https://dev.to/tmchuynh/introducing-vanilla-calendar-pro-a-simple-customizable-javascript-calendar-library-4c4n",
      "created_at": "2024-11-03T21:45:34Z",
      "edited_at": "2024-11-03T22:05:09Z",
      "crossposted_at": null,
      "published_at": "2024-11-14T00:45:00Z",
      "last_comment_at": "2024-11-14T00:45:00Z",
      "reading_time_minutes": 5,
      "tag_list": [
        "webdev",
        "frontend",
        "beginners",
        "tutorial"
      ],
      "tags": "webdev, frontend, beginners, tutorial",
      "user": {
        "name": "Tina Huynh",
        "username": "tmchuynh",
        "twitter_username": null,
        "github_username": "tmchuynh",
        "user_id": 820815,
        "website_url": "http://tmchuynh.me/",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F820815%2F57e1ef18-1563-4810-9d8c-f5cf87d1dcb9.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F820815%2F57e1ef18-1563-4810-9d8c-f5cf87d1dcb9.jpg"
      }
    },
    {
      "type_of": "article",
      "id": 2147959,
      "title": "Meme Monday",
      "description": "Meme Monday!  Today's cover image comes from last week's thread.  DEV is an inclusive space! Humor in...",
      "readable_publish_date": "Dec 9",
      "slug": "meme-monday-kem",
      "path": "/ben/meme-monday-kem",
      "url": "https://dev.to/ben/meme-monday-kem",
      "comments_count": 43,
      "public_reactions_count": 39,
      "collection_id": null,
      "published_timestamp": "2024-12-09T14:53:26Z",
      "positive_reactions_count": 39,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fnp9xz0gjs8bjyc6j02lf.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fnp9xz0gjs8bjyc6j02lf.png",
      "canonical_url": "https://dev.to/ben/meme-monday-kem",
      "created_at": "2024-12-09T14:53:27Z",
      "edited_at": null,
      "crossposted_at": null,
      "published_at": "2024-12-09T14:53:26Z",
      "last_comment_at": "2024-12-18T20:55:28Z",
      "reading_time_minutes": 1,
      "tag_list": [
        "discuss",
        "jokes",
        "watercooler"
      ],
      "tags": "discuss, jokes, watercooler",
      "user": {
        "name": "Ben Halpern",
        "username": "ben",
        "twitter_username": "bendhalpern",
        "github_username": "benhalpern",
        "user_id": 1,
        "website_url": "http://benhalpern.com",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1%2Ff451a206-11c8-4e3d-8936-143d0a7e65bb.png",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1%2Ff451a206-11c8-4e3d-8936-143d0a7e65bb.png"
      },
      "flare_tag": {
        "name": "discuss",
        "bg_color_hex": "#71EA8B",
        "text_color_hex": "#FFFFFF"
      }
    },
    {
      "type_of": "article",
      "id": 2154914,
      "title": "Autopost to Bluesky and Mastodon by API",
      "description": "Last time we learned how to verify our accounts using a domain with a free Glitch website – this time...",
      "readable_publish_date": "Dec 13",
      "slug": "autopost-to-bluesky-and-mastodon-by-api-500d",
      "path": "/glitch/autopost-to-bluesky-and-mastodon-by-api-500d",
      "url": "https://dev.to/glitch/autopost-to-bluesky-and-mastodon-by-api-500d",
      "comments_count": 0,
      "public_reactions_count": 8,
      "collection_id": null,
      "published_timestamp": "2024-12-13T16:14:14Z",
      "positive_reactions_count": 8,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fd1wpbbg4dykux1q3i5ct.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fd1wpbbg4dykux1q3i5ct.png",
      "canonical_url": "https://dev.to/glitch/autopost-to-bluesky-and-mastodon-by-api-500d",
      "created_at": "2024-12-13T11:50:06Z",
      "edited_at": null,
      "crossposted_at": null,
      "published_at": "2024-12-13T16:14:14Z",
      "last_comment_at": "2024-12-13T16:14:14Z",
      "reading_time_minutes": 5,
      "tag_list": [
        "webdev",
        "socialmedia",
        "api",
        "node"
      ],
      "tags": "webdev, socialmedia, api, node",
      "user": {
        "name": "Sue Smith",
        "username": "suesmith",
        "twitter_username": null,
        "github_username": "SueSmith",
        "user_id": 154099,
        "website_url": "https://www.suesmith.dev/",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F154099%2F9d185df0-7f11-45be-a0d9-a24997721513.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F154099%2F9d185df0-7f11-45be-a0d9-a24997721513.jpg"
      },
      "organization": {
        "name": "Glitch",
        "username": "glitch",
        "slug": "glitch",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F609%2F21477ab0-e36f-4e4a-a02a-7074a782d4f2.png",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F609%2F21477ab0-e36f-4e4a-a02a-7074a782d4f2.png"
      }
    },
    {
      "type_of": "article",
      "id": 2134016,
      "title": "Top 7 Featured DEV Posts of the Week",
      "description": "Welcome to this week's Top 7, where the DEV editorial team handpicks their favorite posts from the...",
      "readable_publish_date": "Dec 3",
      "slug": "top-7-featured-dev-posts-of-the-week-4hna",
      "path": "/devteam/top-7-featured-dev-posts-of-the-week-4hna",
      "url": "https://dev.to/devteam/top-7-featured-dev-posts-of-the-week-4hna",
      "comments_count": 7,
      "public_reactions_count": 15,
      "collection_id": null,
      "published_timestamp": "2024-12-03T16:09:48Z",
      "positive_reactions_count": 15,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fdzddn1216kkw38b1k3yy.jpg",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fdzddn1216kkw38b1k3yy.jpg",
      "canonical_url": "https://dev.to/devteam/top-7-featured-dev-posts-of-the-week-4hna",
      "created_at": "2024-12-03T16:09:12Z",
      "edited_at": "2024-12-03T16:10:08Z",
      "crossposted_at": null,
      "published_at": "2024-12-03T16:09:48Z",
      "last_comment_at": "2024-12-04T07:50:19Z",
      "reading_time_minutes": 2,
      "tag_list": [
        "top7"
      ],
      "tags": "top7",
      "user": {
        "name": "dev.to staff",
        "username": "thepracticaldev",
        "twitter_username": "ThePracticalDev",
        "github_username": null,
        "user_id": 3,
        "website_url": "https://dev.to",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png"
      },
      "organization": {
        "name": "The DEV Team",
        "username": "devteam",
        "slug": "devteam",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg"
      }
    },
    {
      "type_of": "article",
      "id": 2101878,
      "title": "what's up fam , its day 01 for me , adding more to my C++ knowledge today and made a mini portfolio that looks hella cool and ez . see you after i do some sh&t #day01 #c++ #javascript",
      "description": "A post by Pratik",
      "readable_publish_date": "Nov 13",
      "slug": "whats-up-fam-its-day-01-for-me-adding-more-to-my-c-knowledge-today-and-made-a-mini-portfolio-that-looks-hella-cool-and-ez-see-you-after-i-do-some-sht-49p8",
      "path": "/coderkun/whats-up-fam-its-day-01-for-me-adding-more-to-my-c-knowledge-today-and-made-a-mini-portfolio-that-looks-hella-cool-and-ez-see-you-after-i-do-some-sht-49p8",
      "url": "https://dev.to/coderkun/whats-up-fam-its-day-01-for-me-adding-more-to-my-c-knowledge-today-and-made-a-mini-portfolio-that-looks-hella-cool-and-ez-see-you-after-i-do-some-sht-49p8",
      "comments_count": 0,
      "public_reactions_count": 3,
      "collection_id": null,
      "published_timestamp": "2024-11-13T05:22:36Z",
      "positive_reactions_count": 3,
      "cover_image": null,
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fjeyx2fyf6e7e8zra0138.png",
      "canonical_url": "https://dev.to/coderkun/whats-up-fam-its-day-01-for-me-adding-more-to-my-c-knowledge-today-and-made-a-mini-portfolio-that-looks-hella-cool-and-ez-see-you-after-i-do-some-sht-49p8",
      "created_at": "2024-11-13T05:22:36Z",
      "edited_at": "2024-11-13T05:23:11Z",
      "crossposted_at": null,
      "published_at": "2024-11-13T05:22:36Z",
      "last_comment_at": "2024-11-13T05:22:36Z",
      "reading_time_minutes": 0,
      "tag_list": [],
      "tags": "",
      "user": {
        "name": "Pratik",
        "username": "coderkun",
        "twitter_username": null,
        "github_username": null,
        "user_id": 2424906,
        "website_url": "https://pratik20gb.github.io/Mini-Portfolio/",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F2424906%2F6722d9ca-1d61-408b-88dd-db56e4f52708.png",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F2424906%2F6722d9ca-1d61-408b-88dd-db56e4f52708.png"
      }
    },
    {
      "type_of": "article",
      "id": 2151621,
      "title": "I Tried Every Hot Programming Language",
      "description": "In this post, I'll make an attempt to compare GoLang, Zig, and Rust. And why Rust wins this...",
      "readable_publish_date": "Dec 13",
      "slug": "i-tried-every-hot-programming-language-514f",
      "path": "/kuvambhardwaj/i-tried-every-hot-programming-language-514f",
      "url": "https://dev.to/kuvambhardwaj/i-tried-every-hot-programming-language-514f",
      "comments_count": 31,
      "public_reactions_count": 186,
      "collection_id": null,
      "published_timestamp": "2024-12-13T05:11:24Z",
      "positive_reactions_count": 186,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fnl0pbkv75lkn3583w0jy.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fnl0pbkv75lkn3583w0jy.png",
      "canonical_url": "https://dev.to/kuvambhardwaj/i-tried-every-hot-programming-language-514f",
      "created_at": "2024-12-11T13:15:41Z",
      "edited_at": "2024-12-13T05:18:47Z",
      "crossposted_at": null,
      "published_at": "2024-12-13T05:11:24Z",
      "last_comment_at": "2024-12-17T20:38:35Z",
      "reading_time_minutes": 5,
      "tag_list": [
        "discuss",
        "rust",
        "go",
        "learning"
      ],
      "tags": "discuss, rust, go, learning",
      "user": {
        "name": "Kuvam Bhardwaj",
        "username": "kuvambhardwaj",
        "twitter_username": null,
        "github_username": "gohashira",
        "user_id": 714377,
        "website_url": "https://github.com/gohashira",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F714377%2F82da1584-a9fe-480b-a583-13907104c9d0.jpeg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F714377%2F82da1584-a9fe-480b-a583-13907104c9d0.jpeg"
      },
      "flare_tag": {
        "name": "discuss",
        "bg_color_hex": "#71EA8B",
        "text_color_hex": "#FFFFFF"
      }
    },
    {
      "type_of": "article",
      "id": 2149509,
      "title": "The Cost of Clinging to Legacy Software: Risks and Realities",
      "description": "Legacy software can be a hidden liability for organizations. Discover why outdated tools persist and the challenges of transitioning to modern solutions.",
      "readable_publish_date": "Dec 10",
      "slug": "the-cost-of-clinging-to-legacy-software-risks-and-realities-2l3i",
      "path": "/bekahhw/the-cost-of-clinging-to-legacy-software-risks-and-realities-2l3i",
      "url": "https://dev.to/bekahhw/the-cost-of-clinging-to-legacy-software-risks-and-realities-2l3i",
      "comments_count": 1,
      "public_reactions_count": 17,
      "collection_id": null,
      "published_timestamp": "2024-12-10T10:46:24Z",
      "positive_reactions_count": 17,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fy76x6oa96ekf23ho6ldn.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fy76x6oa96ekf23ho6ldn.png",
      "canonical_url": "https://dev.to/bekahhw/the-cost-of-clinging-to-legacy-software-risks-and-realities-2l3i",
      "created_at": "2024-12-10T10:46:24Z",
      "edited_at": "2024-12-10T18:36:36Z",
      "crossposted_at": null,
      "published_at": "2024-12-10T10:46:24Z",
      "last_comment_at": "2024-12-12T07:55:07Z",
      "reading_time_minutes": 3,
      "tag_list": [
        "opensource",
        "community"
      ],
      "tags": "opensource, community",
      "user": {
        "name": "BekahHW",
        "username": "bekahhw",
        "twitter_username": "BekahHW",
        "github_username": "BekahHW",
        "user_id": 345658,
        "website_url": "https://bekahhw.com/",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F345658%2Fa72b6b8b-b954-47fb-8919-ab380905f26b.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F345658%2Fa72b6b8b-b954-47fb-8919-ab380905f26b.jpg"
      }
    },
    {
      "type_of": "article",
      "id": 2145876,
      "title": "Atomic Note-Taking Guide",
      "description": "What is Atomic Note-Taking?   Atomic note-taking is a method of organizing information into...",
      "readable_publish_date": "Dec 8",
      "slug": "atomic-note-taking-guide-4fo9",
      "path": "/gokayburuc/atomic-note-taking-guide-4fo9",
      "url": "https://dev.to/gokayburuc/atomic-note-taking-guide-4fo9",
      "comments_count": 11,
      "public_reactions_count": 69,
      "collection_id": null,
      "published_timestamp": "2024-12-08T17:45:54Z",
      "positive_reactions_count": 69,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Foudhqgw7b5s0qns6oqib.jpg",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Foudhqgw7b5s0qns6oqib.jpg",
      "canonical_url": "https://dev.to/gokayburuc/atomic-note-taking-guide-4fo9",
      "created_at": "2024-12-08T17:45:55Z",
      "edited_at": null,
      "crossposted_at": null,
      "published_at": "2024-12-08T17:45:54Z",
      "last_comment_at": "2024-12-14T19:02:46Z",
      "reading_time_minutes": 7,
      "tag_list": [
        "productivity",
        "vim",
        "neovim",
        "obsidian"
      ],
      "tags": "productivity, vim, neovim, obsidian",
      "user": {
        "name": "gokayburuc.dev",
        "username": "gokayburuc",
        "twitter_username": null,
        "github_username": "gokayburuc",
        "user_id": 195090,
        "website_url": "https://www.linkedin.com/in/gokayburuc",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F195090%2Fa9e94ba1-65a6-4130-b384-26f616e4c5ce.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F195090%2Fa9e94ba1-65a6-4130-b384-26f616e4c5ce.jpg"
      }
    },
    {
      "type_of": "article",
      "id": 2148408,
      "title": "AI Generating a 3d Print",
      "description": "Quickly take an AI generated image and make it a 3d print with the following steps.   Generate an...",
      "readable_publish_date": "Dec 9",
      "slug": "ai-generating-a-3d-print-2e76",
      "path": "/ryanlanciaux/ai-generating-a-3d-print-2e76",
      "url": "https://dev.to/ryanlanciaux/ai-generating-a-3d-print-2e76",
      "comments_count": 6,
      "public_reactions_count": 15,
      "collection_id": null,
      "published_timestamp": "2024-12-09T18:27:25Z",
      "positive_reactions_count": 15,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fybkoiuad5ff33ry4orjr.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fybkoiuad5ff33ry4orjr.png",
      "canonical_url": "https://dev.to/ryanlanciaux/ai-generating-a-3d-print-2e76",
      "created_at": "2024-12-09T18:27:26Z",
      "edited_at": null,
      "crossposted_at": null,
      "published_at": "2024-12-09T18:27:25Z",
      "last_comment_at": "2024-12-12T00:01:32Z",
      "reading_time_minutes": 1,
      "tag_list": [
        "ai",
        "3dprinting",
        "3dmodel",
        "imadethis"
      ],
      "tags": "ai, 3dprinting, 3dmodel, imadethis",
      "user": {
        "name": "Ryan Lanciaux",
        "username": "ryanlanciaux",
        "twitter_username": "ryanlanciaux",
        "github_username": "ryanlanciaux",
        "user_id": 34114,
        "website_url": "https://ryanlanciaux.com/",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F34114%2Fcf821a04-560b-42d3-8ff1-3646e5e62261.jpeg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F34114%2Fcf821a04-560b-42d3-8ff1-3646e5e62261.jpeg"
      }
    },
    {
      "type_of": "article",
      "id": 2139322,
      "title": "Congrats to the AssemblyAI Challenge Winners!",
      "description": "The wait is over! We are excited to announce the winners of the AssemblyAI Challenge.  From musical...",
      "readable_publish_date": "Dec 5",
      "slug": "congrats-to-the-assemblyai-challenge-winners-5f8a",
      "path": "/devteam/congrats-to-the-assemblyai-challenge-winners-5f8a",
      "url": "https://dev.to/devteam/congrats-to-the-assemblyai-challenge-winners-5f8a",
      "comments_count": 13,
      "public_reactions_count": 47,
      "collection_id": null,
      "published_timestamp": "2024-12-05T19:15:50Z",
      "positive_reactions_count": 47,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F9j6ek3jr959jps2swcpm.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F9j6ek3jr959jps2swcpm.png",
      "canonical_url": "https://dev.to/devteam/congrats-to-the-assemblyai-challenge-winners-5f8a",
      "created_at": "2024-12-05T19:09:41Z",
      "edited_at": null,
      "crossposted_at": null,
      "published_at": "2024-12-05T19:15:50Z",
      "last_comment_at": "2024-12-11T12:29:48Z",
      "reading_time_minutes": 2,
      "tag_list": [
        "devchallenge",
        "assemblyaichallenge",
        "ai",
        "api"
      ],
      "tags": "devchallenge, assemblyaichallenge, ai, api",
      "user": {
        "name": "dev.to staff",
        "username": "thepracticaldev",
        "twitter_username": "ThePracticalDev",
        "github_username": null,
        "user_id": 3,
        "website_url": "https://dev.to",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png"
      },
      "organization": {
        "name": "The DEV Team",
        "username": "devteam",
        "slug": "devteam",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg"
      }
    },
    {
      "type_of": "article",
      "id": 2150531,
      "title": "Connecting AI Agents to Your Systems with MCP",
      "description": "Learn how MCP standardizes integrations and fosters an ecosystem for the future of AI-enabled tools.",
      "readable_publish_date": "Dec 10",
      "slug": "connecting-ai-agents-to-your-systems-with-mcp-458h",
      "path": "/techgirl1908/connecting-ai-agents-to-your-systems-with-mcp-458h",
      "url": "https://dev.to/techgirl1908/connecting-ai-agents-to-your-systems-with-mcp-458h",
      "comments_count": 0,
      "public_reactions_count": 17,
      "collection_id": null,
      "published_timestamp": "2024-12-10T22:12:26Z",
      "positive_reactions_count": 17,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fmb4z82qq9btav4w08fjf.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fmb4z82qq9btav4w08fjf.png",
      "canonical_url": "https://block.github.io/goose/blog/2024/12/10/connecting-ai-agents-to-your-systems-with-mcp.html",
      "created_at": "2024-12-10T22:11:50Z",
      "edited_at": null,
      "crossposted_at": null,
      "published_at": "2024-12-10T22:12:26Z",
      "last_comment_at": "2024-12-10T22:12:26Z",
      "reading_time_minutes": 3,
      "tag_list": [
        "ai",
        "aiagent",
        "mcp",
        "goose"
      ],
      "tags": "ai, aiagent, mcp, goose",
      "user": {
        "name": "Angie Jones",
        "username": "techgirl1908",
        "twitter_username": "techgirl1908",
        "github_username": "angiejones",
        "user_id": 18472,
        "website_url": "http://angiejones.tech",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F18472%2F274a10e2-6b72-4dbb-9f3d-35335669c706.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F18472%2F274a10e2-6b72-4dbb-9f3d-35335669c706.jpg"
      }
    },
    {
      "type_of": "article",
      "id": 2148565,
      "title": "🎄Have Yourself a Quizzy Little Christmas🎄 writeup",
      "description": "Have yourself a QUIZZY little Christmas Let your heart be light Next year all our troubles will...",
      "readable_publish_date": "Dec 10",
      "slug": "have-yourself-a-quizzy-little-christmas-writeup-44fi",
      "path": "/whykay/have-yourself-a-quizzy-little-christmas-writeup-44fi",
      "url": "https://dev.to/whykay/have-yourself-a-quizzy-little-christmas-writeup-44fi",
      "comments_count": 1,
      "public_reactions_count": 5,
      "collection_id": 29726,
      "published_timestamp": "2024-12-10T17:18:11Z",
      "positive_reactions_count": 5,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F7ar9yoafdge1mgqufhve.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F7ar9yoafdge1mgqufhve.png",
      "canonical_url": "https://dev.to/whykay/have-yourself-a-quizzy-little-christmas-writeup-44fi",
      "created_at": "2024-12-09T20:28:37Z",
      "edited_at": "2024-12-12T14:35:36Z",
      "crossposted_at": null,
      "published_at": "2024-12-10T17:18:11Z",
      "last_comment_at": "2024-12-11T00:45:43Z",
      "reading_time_minutes": 4,
      "tag_list": [
        "irishtechcommunity",
        "community",
        "techcommunity"
      ],
      "tags": "irishtechcommunity, community, techcommunity",
      "user": {
        "name": "whykay 👩🏻\u200d💻🐈🏳️\u200d🌈 (she/her)",
        "username": "whykay",
        "twitter_username": "whykay",
        "github_username": "whykay",
        "user_id": 407879,
        "website_url": "https://beacons.page/whykay",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F407879%2Fc6e55af6-63e1-4173-bb8c-e504a2a861ad.jpg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F407879%2Fc6e55af6-63e1-4173-bb8c-e504a2a861ad.jpg"
      }
    }
  ]